language: go
go:
  - 1.3.3
  - 1.4.2
  - tip
env: TESTARCH=amd64
script:
  - bin/fetch-configlet
  - bin/configlet .
  - GOARCH=$TESTARCH go test -cpu 2 --tags example  ./...
matrix:
  include:
    - go: tip
      env: TESTARCH=386
